//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialNetworkTest2021.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocialNetworkTest2021Entities : DbContext
    {
        public SocialNetworkTest2021Entities()
            : base("name=SocialNetworkTest2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<FriendList> FriendList { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<PostMsg> PostMsg { get; set; }
    }
}
